// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: order.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *OrderReq) Validate() error {
	return nil
}
func (this *OrderResp) Validate() error {
	return nil
}
