// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductReq) Reset()         { *m = ProductReq{} }
func (m *ProductReq) String() string { return proto.CompactTextString(m) }
func (*ProductReq) ProtoMessage()    {}
func (*ProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_0790209a64f0b232, []int{0}
}
func (m *ProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductReq.Unmarshal(m, b)
}
func (m *ProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductReq.Marshal(b, m, deterministic)
}
func (dst *ProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductReq.Merge(dst, src)
}
func (m *ProductReq) XXX_Size() int {
	return xxx_messageInfo_ProductReq.Size(m)
}
func (m *ProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProductReq proto.InternalMessageInfo

func (m *ProductReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProductResp struct {
	ProductId            int32    `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductResp) Reset()         { *m = ProductResp{} }
func (m *ProductResp) String() string { return proto.CompactTextString(m) }
func (*ProductResp) ProtoMessage()    {}
func (*ProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_0790209a64f0b232, []int{1}
}
func (m *ProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResp.Unmarshal(m, b)
}
func (m *ProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResp.Marshal(b, m, deterministic)
}
func (dst *ProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResp.Merge(dst, src)
}
func (m *ProductResp) XXX_Size() int {
	return xxx_messageInfo_ProductResp.Size(m)
}
func (m *ProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResp proto.InternalMessageInfo

func (m *ProductResp) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ProductResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ProductReq)(nil), "proto.ProductReq")
	proto.RegisterType((*ProductResp)(nil), "proto.ProductResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductClient is the client API for Product service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductClient interface {
	PostProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*ProductResp, error)
}

type productClient struct {
	cc *grpc.ClientConn
}

func NewProductClient(cc *grpc.ClientConn) ProductClient {
	return &productClient{cc}
}

func (c *productClient) PostProduct(ctx context.Context, in *ProductReq, opts ...grpc.CallOption) (*ProductResp, error) {
	out := new(ProductResp)
	err := c.cc.Invoke(ctx, "/proto.Product/PostProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServer is the server API for Product service.
type ProductServer interface {
	PostProduct(context.Context, *ProductReq) (*ProductResp, error)
}

func RegisterProductServer(s *grpc.Server, srv ProductServer) {
	s.RegisterService(&_Product_serviceDesc, srv)
}

func _Product_PostProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).PostProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Product/PostProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).PostProduct(ctx, req.(*ProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Product_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostProduct",
			Handler:    _Product_PostProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_product_0790209a64f0b232) }

var fileDescriptor_product_0790209a64f0b232 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x32, 0xe9,
	0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89,
	0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x45, 0x52, 0x66, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a,
	0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0xe5, 0x99, 0x25, 0xd9, 0xf9, 0xe5, 0xfa, 0xe9, 0xf9, 0xba, 0x60,
	0x49, 0xdd, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0xfc, 0xa2, 0x62, 0x7d, 0x38, 0x13, 0xa2,
	0x4f, 0x49, 0x81, 0x8b, 0x2b, 0x00, 0x62, 0x5b, 0x50, 0x6a, 0xa1, 0x90, 0x10, 0x17, 0x4b, 0x5e,
	0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xe4, 0xc0, 0xc5, 0x0d,
	0x57, 0x51, 0x5c, 0x20, 0x24, 0xcb, 0xc5, 0x05, 0x75, 0x5e, 0x7c, 0x66, 0x0a, 0x58, 0x21, 0x6b,
	0x10, 0x27, 0x54, 0xc4, 0x33, 0x05, 0x6e, 0x02, 0x13, 0xc2, 0x04, 0xa3, 0x08, 0x2e, 0x76, 0xa8,
	0x09, 0x42, 0xbe, 0x5c, 0xdc, 0x01, 0xf9, 0xc5, 0x25, 0x30, 0xae, 0x20, 0xc4, 0x15, 0x7a, 0x08,
	0x27, 0x48, 0x09, 0xa1, 0x0b, 0x15, 0x17, 0x28, 0x89, 0x37, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x50,
	0x89, 0x47, 0xbf, 0x20, 0xbf, 0xb8, 0x04, 0x6a, 0x99, 0x15, 0xa3, 0x56, 0x12, 0x1b, 0x58, 0xad,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x87, 0xeb, 0xfb, 0x32, 0x01, 0x00, 0x00,
}
